#!/usr/bin/env python3
try:
    from cli import cli         # for running after build and install
except:
    from src.cli import cli     # for running after build and install

if __name__ == "__main__":
    cli()  # call cli command ground run file is run